name: cicd_with_sonarqube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run tests
        run: python -m unittest discover -s tests

  sonarqube:
    name: SonarQube Scan
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://remodeler-unearth-rented.ngrok-free.dev
        with:
          skipSignatureVerification: true # This removes the warning
          args: >
            -Dsonar.projectKey=calculator-app
            -Dsonar.scanner.skipSslVerification=true
